# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
#sudo: false
cache: packages
warnings_are_errors: false

#r_github_packages:
#  - jimhester/covr

after_success:
 # - bash <(curl -s https://codecov.io/bash) && Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
